version: '3.7'

services:
  eureka-server:
    build: ./service-registry
    image: elenapan/eureka-registry:latest
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  stock_exchange_analyst:
    build: ./stock_exchange_analyst_ms
    image: elenapan/analyst-ms:latest
    depends_on:
      - eureka-server
    volumes:
      - ./src/main/resources/db:/app/src/main/resources/db
      - ./src/main/resources/ta:/app/src/main/resources/ta
      - ./src/main/resources/pred:/app/src/main/resources/pred
      - ./src/main/resources/sent:/app/src/main/resources/sent
      - ./src/main/resources/python-scripts:/app/src/main/resources/python-scripts
    ports:
      - "8080:8080"
    networks:
      - eureka-network

  company_stock_microservice:
    build: ./company_stock_microservice
    image: elenapan/stock-ms:latest
    depends_on:
      - eureka-server
      - stock_exchange_analyst
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    volumes:
      - ./src/main/resources/db:/app/src/main/resources/db:ro
    ports:
      - "9071:9071"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
